with-expecter: true
filename: "mock_{{.InterfaceName}}_test.go"
all: false

dir: "{{.InterfaceDir}}"
outpkg: "{{.PackageName}}"
inpackage: True

packages:
  github.com/ichenhe/cert-deployer/domain:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocker"
      outpkg: "mocker"
      inpackage: False
      include-regex: ".*"
      exclude-regex: ".*Func"
  github.com/ichenhe/cert-deployer/cmd/app:
    interfaces:
      assetDeployer: { }
      commandExecutor: { }
  github.com/ichenhe/cert-deployer/deploy:
    interfaces:
      deployerCommander: { }
  github.com/ichenhe/cert-deployer/trigger/filetrigger:
    interfaces:
      fileMonitor: { }
  github.com/ichenhe/cert-deployer/plugins/aws:
    interfaces:
      acmApi: { }
      acmManager: { }
      cloudfrontApi: { }
