log:
  # whether to export to a file
  enable-file: false
  # the directory where the log files are saved
  file-dir: ./log
  # debug / info / warn / error
  level: info

cloud-providers:
  example:
    # 'provider' must be in the support list
    provider: TencentCloud
    secret-id: "xxxxxxxxxxxxxxxxxxxxx"
    secret-key: "xxxxxxxxxxxxxxxxxxxxx"

deployments:
  tencent-cdn:
    provider-id: example
    cert: "/fullchain.pem"
    key: "/private.pem"
    assets:
      - type: cdn
        id: "xxx"

triggers:
  cert:
    type: file_monitoring
    deployments: [ "tencent-cdn" ]
    options:
      file: "/path/to/cert.pem"
      wait: 1000
